### ISSUE TITLE
alternative way to request properties in text queries

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-base#16]
What I'm trying to solve is the problem of queries that we need to write like this:

```sparql
select ?foo where {
  {
     (?s ?sc ?lit) text:query ( rdfs:label ?L_NAME "highlight:" ).
  }
  union
  {
    (?TT ?sc ?lit2) text:query ( skos:altLabel ?L_NAME "highlight:" ).
  }
  union
  { 
    (?TT ?sc ?lit1) text:query ( skos:prefLabel ?L_NAME "highlight:").
  }
}
```

and so on for every field. While it might be useful in some cases to discriminate between these, the only discrimination we make in our queries is between:
- names / titles (using `rdfs:label`)
- etext chunks (using `:chunkContents`)
- entity labels (using `skos:prefLabel` and `skos:altLabel`)
- the rest (which we actually never really query)

There is a mapping between properties and Lucene fields in [the configuration](https://github.com/buda-base/buda-base/blob/master/conf/fuseki/ttl.erb#L394). I'm wondering if we could leverage that to map multiple properties (like `skos:prefLabel` and `skos:altLabel` in a first time) to the same Lucene field, so that when we search on `skos:prefLabel` is actually finds both? 

I'm thinking that a more accurate way would be to query on the Lucene field name actually, it makes less sense from a LOD perspective, but it's closer to reality... changing the configuration to something like:

```ttl
text:map (
         [ text:field "label" ;
           text:fieldUri bdo:label ;
           text:predicate skos:prefLabel ]
```

and query something like:

```sparql
(?s ?sc ?lit) bdo:label ( rdfs:label ?L_NAME "highlight:" ).
```

that way we fully understand what's going on...

**Comment by xristy** [comment]
It should be possible to write a query like:
```
(?chunk ?score ?lit) text:query ( "(label:\"de bzhin gshegs\" OR altLabel:\"de bzhin gshegs\" OR rdfsLabel:\"de bzhin gshegs\")" 10 "lang:bo-x-ewts" "highlight:") .
```

but the QueryParser needs some work. Note: the `OR`s are added for clarity and aren't otherwise needed.

If I can make this work (as I believe it should) then it pushes the `UNION`s into Lucene.

Would this approach help?

It is also be possible to configure like:
```
    text:map (
         [ text:field "label" ; 
           text:predicate skos:prefLabel ]
         [ text:field "label" ; 
           text:predicate skos:altLabel ; ]
         [ text:field "label" ;
           text:predicate rdfs:label ; ]
```
so that all three RDF properties appear under a single Lucene field. That would preclude separating triples when desired unless it's possible to map a single RDF property to more than one Lucene field which I have to check on.

**Comment by eroux** [comment]
oh having the query with the OR would be most excellent yes!

For the mappings, what about changing the config to the following one?

```ttl
bdo:foo    text:map (
         [ text:field "skoslabel" ; 
           text:predicate skos:prefLabel ]
         [ text:field "skoslabel" ; 
           text:predicate skos:altLabel ; ]
         [ text:field "rdfsLabel" ;
           text:predicate rdfs:label ; ]
         [ text:field "chunkContents" ;
           text:predicate bdo:chunkContents ; ]
         [ text:field "otherfield" ;
           text:predicate bdo:eTextTitle ; ]
         [ text:field "otherfield" ;
           text:predicate adm:logMessage ; ]
         [ text:field "otherfield" ;
           text:predicate bdo:noteText ; ]
         [ text:field "otherfield" ;
           text:predicate bdo:workAuthorshipStatement ; ]
         [ text:field "otherfield" ; 
           text:predicate bdo:workColophon ; ]
         [ text:field "otherfield" ;
           text:predicate bdo:workEditionStatement ; ]
         [ text:field "otherfield" ;
           text:predicate bdo:workPublisherLocation ; ]
         [ text:field "otherfield" ;
           text:predicate bdo:workPublisherName ; ]
         [ text:field "otherfield" ;
           text:predicate bdo:workSeriesName ; ]
         ) ;
    .
```

then we could search on the `otherfield` field in some requests (we currently don't)

**Comment by xristy** [comment]
I think I can make the following work reasonably:
```
(?chunk ?score ?lit) text:query 
    ( text:props
      skos:prefLabel skos:altLabel rdfs:label ""\"de bzhin gshegs\"" 
      10 "lang:bo-x-ewts" "highlight:") .
```

and then add the ability to define a list of properties that will be used in an OR in the Lucene query:
```
   text:propList [ text:listId  bdo:labels ;
                            text:props ( skos:prefLabel skos:altLabel rdfs:label ) ]
```

and then use like:
```
    (?chunk ?score ?lit) text:query 
        ( text:props bdo:labels ""\"de bzhin gshegs\"" 10 "lang:bo-x-ewts" "highlight:") .
```

this approach avoids mapping multiple properties to the same Lucene field which has a problem that only by changing the config and re-indexing would we be able to separate out particular properties if we need to query on them independently.

It is also worth mentioning that we can already do queries like:
```
(?chunk ?score ?lit) text:query ( rdfs:label "( \"de bzhin gshegs\" AND (\"'bum\" OR \"rdo rje\"))" 20 "lang:bo-x-ewts" "highlight:")
```

**Comment by eroux** [comment]
ok yes, what do you think of my [proposed](https://github.com/buda-base/buda-base/issues/16#issuecomment-499967154) prop / field map?

**Comment by xristy** [comment]
Your [proposal](https://github.com/buda-base/buda-base/issues/16#issuecomment-499967154) to map `bdo:noteText`, `bdo:workColophon`, and so on to a single Lucene field, `otherField`, effectively does an `OR`, and it also has the effect that if one wants to search just colophons then the `text:query` results need to be filtered at the sparql level to ignore all but the colophon matches.

Avoiding the filters to search just on colophons requires to separate out the colophons by changing the config and re-indexing.

On the other hand the proposed property list implementation accomplishes the `OR` at the Lucene level while keeping the various properties separated as far as Lucene fields. It goes like this:
```
    <#indexLucene> a text:TextIndexLucene ;
        text:directory <file:Lucene> ;
        text:entityMap <#entMap> ;
        text:propLists (
            [ text:propListProp bdo:labels ;
              text:props ( skos:prefLabel 
                           skos:altLabel 
                           rdfs:label ) ;
            ]
            [ text:propListProp bdo:workStmts ;
              text:props ( bdo:workColophon 
                           bdo:workAuthorshipStatement 
                           bdo:workEditionStatement ) ;
            ]
            [ text:propListProp bdo:others ;
              text:props ( bdo:workColophon 
                           bdo:workAuthorshipStatement 
                           bdo:workPublisherName
                           bdo:workSeriesName
                           bdo:workEditionStatement
                           bdo:eTextTitle
                           bdo:noteText
                           bdo:logMessage
                           bdo:workPublisherLocation ) ;
            ]
        )
        text:defineAnalyzers (
            [text:addLang "sa-x-iast" ;
             text:analyzer [ . . . ]]
            [text:defineAnalyzer <#foo> ;
             text:analyzer [ . . . ]]
        )
```

so then `text:query` can be used in a variety of ways:
```
?s text:query (text:props bdo:others "\"de zhin gshegs\""@bo-x-ewts)
```

or
```
?s text:query (text:props bdo:workStmts "\"de zhin gshegs\""@bo-x-ewts)
```

or
```
?s text:query (bdo:workColophon "\"de zhin gshegs\""@bo-x-ewts)
```

w/o having to use filters at sparql level or reconfiguring and re-indexing. Also if it we want to search on the `bdo:workStmts` and on `bdo:noteText` all that is needed is:
```
?s text:query (text:props bdo:workStmts bdo:noteText "\"de zhin gshegs\""@bo-x-ewts)
```

since the implementation allows to follow `text:props` w/ a list of properties that may be ontology properties such as `bdo:noteText` and `text:propListProp` properties that identify lists of ontology properties.

**Comment by eroux** [comment]
sure, sounds good! I'm just wondering about the perf hit, but it's probably minor at this point...

**Comment by xristy** [comment]
I've also thought about the performance implications of queries with many `OR` terms. We will be able to look at the impacts of using `unions` at sparql level vs the `OR`s at Lucene. I can also test at some point the mapping of multiple properties to a single field.

I've thought about an approach that allows a single property to be mapped to multiple fields. This sort of approach could allow for flexibility since `bdo:noteText` could be mapped to a `noteText` field in Lucene and to an `otherField`. 

Then there needs to be someway to indicate to `text:query` which field to search on. This might be done by using a similar approach as w/ the `text:props` indicator. 

Making RDF properties one-many is somewhat more involved in the `TextIndexLucene` machinery which has properties one-one to fields and fields one-many to properties. Such an approach leads to one-many in both directions. It would increase index storage since each field represents an index, and more space may well bring a significant time savings.

I thought the current proposal would be somewhat more tractable to try initially in an effort to maintain flexibility of querying.

**Comment by eroux** [comment]
sure! let's try it

**Comment by xristy** [comment]
As I pull to the end I see another issue with all approaches: 1) mapping multiple properties to a single field and 2) using the `text:props` approach to `OR`s.

The problem is that we have no way of returning what property matched for each hit. We'll see the subject, score, literal and graph but not the matching predicate/property!

One approach is adding a fifth output param:
```
(?subject ?score ?literal ?graph ?prop) text:query ...
```

Do you see any other solution?

**Comment by eroux** [comment]
Oh, you're right... the param solution looks like a good one yes

**Comment by xristy** [comment]
Unfortunately I don't see how it will work with:

>1) mapping multiple properties to a single field

It "works" with the `text:props` so long as each property is mapped to a single field.

**Comment by eroux** [comment]
In this case the property could be encoded in a separate field in the document perhaps?
