### ISSUE TITLE
remove diacritics in mutlilingual analyzer

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-base#22]
In the mutli-lingual analyzer, it would be useful to have a mechanism that removes diacritics so that more hits are returned for Sanskrit, Pinyin, etc.

**Comment by eroux** [comment]
I think this would mean using the ASCIIFoldingFilter and LowerCaseFilter in the analyzer we use for the general cases (like en, mixed, etc.). @xristy am I right to say that we would need to create our own custom analyzer for this? Or can we put some custom Lucene filters in a pipeline in the assembly file?

**Comment by xristy** [comment]
when is the diacritic (and chars like `-` and so on) removal wanted? 

- [ ] all lang tags, 
- [ ] strings without lang tags, 
- [ ] strings with specific lang tags?

Define a ConfigurableAnalyzer:
```
text:analyzer [
  a text:ConfigurableAnalyzer ;
  text:tokenizer text:KeywordTokenizer ;
  text:filters (text:ASCIIFoldingFilter, text:LowerCaseFilter)
]
```
as a default analyzer for use when no lang tag is present or the lang tag doesn't have an analyzer defined. The default analyzer for `MultilingualAnalyzer` is the Lucene `StandardAnalyzer`. The above definition placed at the top of the `text:TextIndexLucene` configuration in the assembler file will replace the `StandardAnalyzer` as the default.

I recall mention of applying something like this to isbns and other such fields which could be handled by defining the use of such an analyzer on specific properties.

As I understand, there are already configurations defined of lucene-sa and lucene-zh that handle some of these diacritics-folded needs.

I'm not sure of the specific needs.

**Comment by eroux** [comment]
ah excellent, thanks! I was thinking about replacing the default analyzer by that yes, so that all the tags that are not handled by other analyzers can go through that. That will pose a few problems for Khmer (perhaps?) but we can deal with that at a later point... or we could restrict this new analyzer to `en` and `bo-x-mixed` (I think it's that one)

**Comment by xristy** [comment]
Do `en` and `bo-x-mixed` have diacritics (I suppose `'` could be considered a diacritic)? I think I'm confused regarding the term diacritics.

What about isbn and lccn and so on where there was a desire to delete hyphens and such? The [ASCIIFoldingFilter](https://lucene.apache.org/core/7_7_0/analyzers-common/org/apache/lucene/analysis/miscellaneous/ASCIIFoldingFilter.html) actually won't touch hyphen-minus (`U002D`) since its already in the _Basic Latin_.

As long as Khmer romanized strings are tagged then the default analyzer shouldn't be triggered if there's a specific analyzer configured for the Khmer tags -`km-x-efeo` or whatever.

**Comment by eroux** [comment]
sometimes titles in English have diacritics if they have transliteration of Tibetan or Sanskrit yes (`'` could be removed but it's not of primary priority I think). It's not that common though... I think having the analyzer you described for `en` and `bo-x-mixed` will be good, thanks!

**Comment by xristy** [comment]
see #34
